### ISSUE TITLE
Need help with feature implementation issues

### ISSUE THREAD

**Issue by Tank-zhu** [FontoXML/dita-example-editor#56]
1. First, I want to add a button that can change the color of the document content font

![image](https://github.com/FontoXML/dita-example-editor/assets/10337065/a30991a2-0a38-4751-af96-52213bfa74dd)

2. The second question is to export the edited document into pdf

**Comment by Tank-zhu** [comment]
Can you give me a demo? Thank you

**Comment by bwrrp** [comment]
Hi,

This repository is an example configuration for the DITA schema. DITA does not support setting text color natively in its schema. It is possible to adjust the color through the `outputclass` attribute and custom styling, but this is not in scope for this example as we prefer markup that has semantic value rather than only controlling the appearance of content.

Exporting a document to PDF is usually handled on the backend by external software. This is not covered by the editor configuration.

For future support questions or demo requests, please use our [support desk](https://support.fontoxml.com).
